apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-import-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vm-import-operator
  template:
    metadata:
      labels:
        name: vm-import-operator
    spec:
      serviceAccountName: vm-import-operator
      containers:
        - name: vm-import-operator
          # Replace this with the built image name
          image: quay.io/kubevirt/vm-import-operator
          command:
          - vm-import-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vm-import-operator"
